apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-local-dns.fullname" . }}-upstream
  namespace: kube-system
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
spec:
  ports:
  - name: dns
    port: {{ .Values.config.dnsPort }}
    protocol: UDP
    targetPort: {{ .Values.config.dnsPort }}
  - name: dns-tcp
    port: {{ .Values.config.dnsPort }}
    protocol: TCP
    targetPort: {{ .Values.config.dnsPort }}
  selector:
    k8s-app: kube-dns
